apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch-operator
    release: elasticsearch-operator
  name: elasticsearch-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: elasticsearch-operator
    release: elasticsearch-operator
  name: elasticsearch-operator
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - create
  - get
  - update
  - delete
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
  - delete
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - create
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - persistentvolumeclaims
  - services
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - update
  - delete
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - deletecollection
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - enterprises.upmc.com
  resources:
  - elasticsearchclusters
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: elasticsearch-operator
    release: elasticsearch-operator
  name: elasticsearch-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-operator
subjects:
- kind: ServiceAccount
  name: elasticsearch-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-operator
    release: elasticsearch-operator
  name: elasticsearch-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-operator
      release: elasticsearch-operator
  template:
    metadata:
      labels:
        app: elasticsearch-operator
        release: elasticsearch-operator
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: upmcenterprises/elasticsearch-operator:0.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
        name: elasticsearch-operator
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: elasticsearch-operator
